---
- name: Criar arquivo de texto no diretório home do usuário
  hosts: localhost
  become: no
  tasks:
    - name: Criar o arquivo teste1.txt
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/teste1.txt"
        state: touch
        mode: '0644'

    - name: Criar o arquivo teste2.txt
          ansible.builtin.file:
            path: "{{ ansible_user_dir }}/teste2.txt"
            state: touch
            mode: '0644'