---
- name: Criar arquivo de texto no diretório home do usuário
  hosts: awx.flinox.com.br
  become: no
  tasks:
    - name: Creating a file with content
      copy:
        dest: "/home/tester/teste2.txt"
        content: |
          linha 01
          linha 02

    - name: Creating an empty file
      file:
        path: "/home/tester/teste1.txt"
        state: touch
        mode: '0644'
